apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbir
  labels:
    app: cbir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cbir
  template:
    metadata:
      labels:
        app: cbir
    spec:
      containers:
      - name: cbir
        image: "{{ .Values.images.cbir }}"
        ports:
        - containerPort: {{ .Values.cbir.port }}
        envFrom:
          - configMapRef:
              name: cbir
