apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  annotations:
    kube-score/ignore: pod-probes
  labels:
    role: redis
    app: {{ include "cytomine.name" . }}
    component: {{ .Release.Name }}-redis
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cytomine.name" . }}-redis
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        role: redis
        app: {{ template "cytomine.name" . }}-redis
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.images.redis }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.redis.port }}
